CREATE DATABASE IF NOT EXISTS ceylon_tourism CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ceylon_tourism;
CREATE TABLE IF NOT EXISTS attractions (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    location VARCHAR(255),
    region VARCHAR(100),
    province VARCHAR(100),
    category VARCHAR(100),
    rating DECIMAL(3, 2) DEFAULT 0.0,
    entrance_fee VARCHAR(100),
    opening_hours VARCHAR(255),
    best_time_to_visit VARCHAR(255),
    coordinates VARCHAR(100),
    image_url TEXT,
    website VARCHAR(255),
    distance_from_colombo INT,
    facilities TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS hotels (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    region VARCHAR(100),
    province VARCHAR(100),
    accommodation_type VARCHAR(100),
    rating DECIMAL(3, 2) DEFAULT 0.0,
    price_range VARCHAR(100),
    amenities TEXT,
    contact VARCHAR(255),
    website VARCHAR(255),
    description TEXT,
    room_count INT,
    check_in_time VARCHAR(50),
    check_out_time VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS restaurants (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    region VARCHAR(100),
    cuisine VARCHAR(100),
    rating DECIMAL(3, 2) DEFAULT 0.0,
    price_range VARCHAR(100),
    specialties TEXT,
    contact VARCHAR(255),
    opening_hours VARCHAR(255),
    description TEXT,
    seating_capacity INT,
    delivery_available BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS beaches (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    region VARCHAR(100),
    province VARCHAR(100),
    description TEXT,
    rating DECIMAL(3, 2) DEFAULT 0.0,
    activities TEXT,
    best_time_to_visit VARCHAR(255),
    facilities TEXT,
    safety_info TEXT,
    water_sports_available BOOLEAN DEFAULT FALSE,
    lifeguard_available BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS cultural_sites (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    region VARCHAR(100),
    province VARCHAR(100),
    type VARCHAR(100),
    description TEXT,
    rating DECIMAL(3, 2) DEFAULT 0.0,
    historical_period VARCHAR(255),
    entrance_fee VARCHAR(100),
    opening_hours VARCHAR(255),
    significance TEXT,
    unesco_site BOOLEAN DEFAULT FALSE,
    dress_code TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS wildlife_parks (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    region VARCHAR(100),
    province VARCHAR(100),
    type VARCHAR(100),
    description TEXT,
    rating DECIMAL(3, 2) DEFAULT 0.0,
    animals_seen TEXT,
    best_time_to_visit VARCHAR(255),
    entrance_fee VARCHAR(100),
    safari_options TEXT,
    area_sqkm DECIMAL(8, 2),
    established_year INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS tea_estates (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    region VARCHAR(100),
    province VARCHAR(100),
    description TEXT,
    rating DECIMAL(3, 2) DEFAULT 0.0,
    tea_types TEXT,
    tour_available BOOLEAN DEFAULT TRUE,
    tasting_available BOOLEAN DEFAULT TRUE,
    entrance_fee VARCHAR(100),
    opening_hours VARCHAR(255),
    established_year INT,
    altitude_m INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS activities (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    region VARCHAR(100),
    category VARCHAR(100),
    description TEXT,
    rating DECIMAL(3, 2) DEFAULT 0.0,
    price_range VARCHAR(100),
    duration VARCHAR(100),
    difficulty_level VARCHAR(50),
    best_time VARCHAR(255),
    equipment_provided BOOLEAN DEFAULT FALSE,
    booking_required BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS transport (
    id INT PRIMARY KEY AUTO_INCREMENT,
    type VARCHAR(100) NOT NULL,
    route VARCHAR(255),
    operator VARCHAR(255),
    description TEXT,
    price_range VARCHAR(100),
    schedule_info TEXT,
    booking_info VARCHAR(255),
    contact VARCHAR(255),
    amenities TEXT,
    duration VARCHAR(100),
    frequency VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS events (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    region VARCHAR(100),
    type VARCHAR(100),
    description TEXT,
    date_period VARCHAR(255),
    significance TEXT,
    activities TEXT,
    visitor_info TEXT,
    entry_fee VARCHAR(100),
    annual_event BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
INSERT INTO attractions (
        name,
        description,
        location,
        region,
        province,
        category,
        rating,
        entrance_fee,
        opening_hours,
        best_time_to_visit,
        distance_from_colombo,
        facilities
    )
VALUES (
        'Sigiriya Rock Fortress',
        'Ancient rock fortress and palace ruins with stunning frescoes and gardens, UNESCO World Heritage Site',
        'Sigiriya',
        'Central',
        'Central Province',
        'Historical',
        4.8,
        'LKR 4500 (Foreign), LKR 60 (Local)',
        '7:00 AM - 5:30 PM',
        'December to April',
        170,
        'Museum, restrooms, parking, guide services'
    ),
    (
        'Temple of the Tooth Relic',
        'Sacred Buddhist temple housing the tooth relic of Buddha, major pilgrimage site',
        'Kandy',
        'Central',
        'Central Province',
        'Religious',
        4.7,
        'LKR 1500 (Foreign), LKR 25 (Local)',
        '5:30 AM - 8:00 PM',
        'Year-round',
        115,
        'Prayer hall, museum, parking, souvenir shop'
    ),
    (
        'Galle Fort',
        'Historic fort built by Portuguese and Dutch with colonial architecture, UNESCO site',
        'Galle',
        'Southern',
        'Southern Province',
        'Historical',
        4.6,
        'Free',
        'Always open',
        'November to April',
        120,
        'Shops, cafes, museums, lighthouse, rampart walk'
    ),
    (
        'Pinnawala Elephant Orphanage',
        'Orphanage and breeding ground for wild Asian elephants',
        'Pinnawala',
        'Sabaragamuwa',
        'Sabaragamuwa Province',
        'Wildlife',
        4.3,
        'LKR 2500 (Foreign), LKR 100 (Local)',
        '8:30 AM - 6:00 PM',
        'Year-round',
        90,
        'Feeding area, river bathing, souvenir shop, restaurant'
    ),
    (
        'Adam\'s Peak (Sri Pada)',
        'Sacred mountain with footprint shrine, popular pilgrimage and hiking destination',
        'Hatton',
        'Central',
        'Central Province',
        'Religious/Adventure',
        4.9,
        'Free',
        '24 hours (season)',
        'December to May',
        180,
        'Rest stops, tea stalls, first aid, lighting during season'
    ),
    (
        'Dambulla Cave Temple',
        'Ancient cave temple complex with Buddha statues and paintings',
        'Dambulla',
        'Central',
        'Central Province',
        'Religious',
        4.6,
        'LKR 1500 (Foreign), LKR 25 (Local)',
        '7:00 AM - 7:00 PM',
        'Year-round',
        148,
        'Museum, parking, restrooms, guide services'
    ),
    (
        'Polonnaruwa Ancient City',
        'Medieval capital with well-preserved ruins and sculptures',
        'Polonnaruwa',
        'North Central',
        'North Central Province',
        'Historical',
        4.5,
        'LKR 3500 (Foreign), LKR 50 (Local)',
        '7:00 AM - 6:00 PM',
        'Year-round',
        216,
        'Bicycle rental, museum, parking, guide services'
    ),
    (
        'Nine Arch Bridge',
        'Iconic railway bridge surrounded by tea plantations and jungle',
        'Ella',
        'Uva',
        'Uva Province',
        'Scenic',
        4.7,
        'Free',
        'Always accessible',
        'December to March',
        200,
        'Viewpoints, tea stalls, parking'
    ),
    (
        'Horton Plains National Park',
        'High-altitude plateau with World\'s End cliff and Baker\'s Falls',
        'Nuwara Eliya',
        'Central',
        'Central Province',
        'Nature',
        4.4,
        'LKR 3000 (Foreign), LKR 60 (Local)',
        '6:00 AM - 6:00 PM',
        'January to March',
        180,
        'Nature trails, information center, parking'
    ),
    (
        'Anuradhapura Sacred City',
        'Ancient capital and sacred city with Buddhist monuments',
        'Anuradhapura',
        'North Central',
        'North Central Province',
        'Religious/Historical',
        4.7,
        'LKR 3500 (Foreign), LKR 50 (Local)',
        '6:00 AM - 6:00 PM',
        'Year-round',
        205,
        'Bicycle rental, museum, restrooms, guide services'
    );
INSERT INTO beaches (
        name,
        location,
        region,
        province,
        description,
        rating,
        activities,
        best_time_to_visit,
        facilities,
        water_sports_available,
        lifeguard_available
    )
VALUES (
        'Mirissa Beach',
        'Mirissa',
        'Southern',
        'Southern Province',
        'Stunning crescent-shaped beach perfect for whale watching and surfing',
        4.8,
        'Whale watching, surfing, swimming, snorkeling, fishing',
        'December to April',
        'Restaurants, hotels, surf schools, boat operators',
        TRUE,
        TRUE
    ),
    (
        'Unawatuna Beach',
        'Unawatuna',
        'Southern',
        'Southern Province',
        'Beautiful curved bay with golden sand and calm waters',
        4.5,
        'Swimming, snorkeling, diving, sunbathing',
        'December to April',
        'Restaurants, guesthouses, dive centers, shops',
        TRUE,
        TRUE
    ),
    (
        'Bentota Beach',
        'Bentota',
        'Western',
        'Western Province',
        'Popular resort town beach with water sports and luxury hotels',
        4.4,
        'Water skiing, jet skiing, windsurfing, river safari',
        'November to April',
        'Luxury resorts, water sports centers, restaurants',
        TRUE,
        TRUE
    ),
    (
        'Arugam Bay',
        'Arugam Bay',
        'Eastern',
        'Eastern Province',
        'World-class surfing destination with consistent waves',
        4.7,
        'Surfing, swimming, wildlife watching, lagoon tours',
        'May to September',
        'Surf schools, backpacker hostels, restaurants',
        TRUE,
        FALSE
    ),
    (
        'Hikkaduwa Beach',
        'Hikkaduwa',
        'Southern',
        'Southern Province',
        'Vibrant beach town with coral reefs and nightlife',
        4.3,
        'Surfing, snorkeling, diving, glass-bottom boat tours',
        'November to April',
        'Hotels, restaurants, dive shops, nightlife',
        TRUE,
        TRUE
    ),
    (
        'Tangalle Beach',
        'Tangalle',
        'Southern',
        'Southern Province',
        'Pristine beach with golden sand and fewer crowds',
        4.6,
        'Swimming, sunbathing, turtle watching, fishing',
        'December to March',
        'Boutique hotels, restaurants, turtle hatchery',
        FALSE,
        FALSE
    ),
    (
        'Negombo Beach',
        'Negombo',
        'Western',
        'Western Province',
        'Beach town near airport with fishing boats and seafood',
        4.2,
        'Swimming, fishing boat tours, kite surfing',
        'December to March',
        'Hotels, restaurants, fish market, churches',
        TRUE,
        TRUE
    ),
    (
        'Pasikudah Beach',
        'Pasikudah',
        'Eastern',
        'Eastern Province',
        'Shallow bay beach perfect for families and water sports',
        4.5,
        'Swimming, water sports, jet skiing, coral viewing',
        'May to September',
        'Resorts, water sports centers, restaurants',
        TRUE,
        TRUE
    );
INSERT INTO hotels (
        name,
        location,
        region,
        province,
        accommodation_type,
        rating,
        price_range,
        amenities,
        description,
        room_count
    )
VALUES (
        'Galle Face Hotel',
        'Colombo',
        'Western',
        'Western Province',
        'Luxury Hotel',
        4.8,
        '$200-400',
        'Swimming pool, spa, multiple restaurants, ocean view, WiFi, gym',
        'Historic luxury hotel facing the Indian Ocean since 1864',
        433
    ),
    (
        'Heritance Kandalama',
        'Dambulla',
        'Central',
        'Central Province',
        'Eco Resort',
        4.9,
        '$150-300',
        'Infinity pool, spa, nature trails, lake view, WiFi, multiple restaurants',
        'Award-winning eco-friendly resort built into rock face',
        152
    ),
    (
        'The Fortress Resort',
        'Galle',
        'Southern',
        'Southern Province',
        'Boutique Resort',
        4.7,
        '$250-500',
        'Private beach, spa, golf course, multiple pools, WiFi, gym',
        'Luxury resort with stunning architecture and ocean views',
        53
    ),
    (
        'Cinnamon Lodge',
        'Habarana',
        'North Central',
        'North Central Province',
        'Wildlife Lodge',
        4.5,
        '$100-200',
        'Swimming pool, safari tours, cultural shows, spa, WiFi',
        'Lodge surrounded by nature with easy access to national parks',
        139
    ),
    (
        'Jetwing Vil Uyana',
        'Sigiriya',
        'Central',
        'Central Province',
        'Eco Lodge',
        4.6,
        '$180-350',
        'Unique wetland setting, spa, nature walks, WiFi, restaurant',
        'Luxury eco-lodge with dwellings over water and paddy fields',
        25
    ),
    (
        'Tea Factory Hotel',
        'Nuwara Eliya',
        'Central',
        'Central Province',
        'Heritage Hotel',
        4.4,
        '$120-250',
        'Mountain views, tea plantation tours, spa, WiFi, restaurant',
        'Converted tea factory with colonial charm in hill country',
        57
    ),
    (
        'Lighthouse Hotel',
        'Galle',
        'Southern',
        'Southern Province',
        'Design Hotel',
        4.5,
        '$200-400',
        'Cliffside location, pool, spa, multiple restaurants, WiFi',
        'Geoffrey Bawa designed hotel overlooking the ocean',
        63
    ),
    (
        'Cinnamon Wild Yala',
        'Yala',
        'Southern',
        'Southern Province',
        'Safari Lodge',
        4.3,
        '$150-280',
        'Safari tours, beachfront location, pool, spa, WiFi',
        'Beachfront safari lodge adjacent to Yala National Park',
        64
    );
INSERT INTO restaurants (
        name,
        location,
        region,
        cuisine,
        rating,
        price_range,
        specialties,
        description,
        opening_hours
    )
VALUES (
        'Ministry of Crab',
        'Colombo',
        'Western',
        'Seafood',
        4.9,
        '$30-60',
        'Mud crab curry, garlic chili crab, black pepper crab, crab roe curry',
        'Award-winning restaurant specializing in Sri Lankan crab dishes',
        '6:00 PM - 12:00 AM'
    ),
    (
        'The Gallery Café',
        'Colombo',
        'Western',
        'International',
        4.6,
        '$15-35',
        'Fusion cuisine, desserts, coffee, pasta, salads',
        'Stylish café in a converted art gallery with contemporary cuisine',
        '10:00 AM - 12:00 AM'
    ),
    (
        'Raja Bojun',
        'Kandy',
        'Central',
        'Traditional Sri Lankan',
        4.4,
        '$5-15',
        'Rice and curry, hoppers, kottu roti, string hoppers, curry varieties',
        'Authentic local restaurant serving traditional Sri Lankan dishes',
        '11:00 AM - 10:00 PM'
    ),
    (
        'Refresh Restaurant',
        'Galle',
        'Southern',
        'Asian Fusion',
        4.3,
        '$10-25',
        'Seafood curry, noodles, fresh juices, Thai curry, local fish',
        'Popular local restaurant with fresh seafood and Asian flavors',
        '7:00 AM - 11:00 PM'
    ),
    (
        'Upali\'s by Nawaloka',
        'Colombo',
        'Western',
        'Sri Lankan',
        4.5,
        '$8-20',
        'Hoppers, kottu, rice and curry, seafood, traditional sweets',
        'Chain restaurant known for authentic Sri Lankan cuisine',
        '11:00 AM - 11:00 PM'
    ),
    (
        'The Lagoon',
        'Cinnamon Grand Colombo',
        'Western',
        'Seafood',
        4.7,
        '$25-50',
        'Fresh seafood, crab curry, prawns, lobster, grilled fish',
        'Upscale seafood restaurant in luxury hotel setting',
        '7:00 PM - 11:00 PM'
    ),
    (
        'Mama\'s Galle Fort Roof Café',
        'Galle',
        'Southern',
        'International',
        4.4,
        '$12-28',
        'Wood-fired pizza, pasta, seafood, cocktails, sunset views',
        'Rooftop café with fort views and international cuisine',
        '11:00 AM - 11:00 PM'
    ),
    (
        'Devon Restaurant',
        'Nuwara Eliya',
        'Central',
        'Indian/Chinese',
        4.2,
        '$8-18',
        'Biryani, fried rice, noodles, curry dishes, Indian bread',
        'Popular local restaurant in hill country with diverse Asian menu',
        '11:00 AM - 10:00 PM'
    );
INSERT INTO cultural_sites (
        name,
        location,
        region,
        province,
        type,
        description,
        rating,
        historical_period,
        entrance_fee,
        opening_hours,
        unesco_site
    )
VALUES (
        'Dambulla Cave Temple',
        'Dambulla',
        'Central',
        'Central Province',
        'Buddhist Temple',
        'Ancient cave temple complex with stunning Buddha statues and paintings',
        4.6,
        '1st Century BC',
        'LKR 1500 (Foreign), LKR 25 (Local)',
        '7:00 AM - 7:00 PM',
        TRUE
    ),
    (
        'Polonnaruwa Ancient City',
        'Polonnaruwa',
        'North Central',
        'North Central Province',
        'Archaeological Site',
        'Medieval capital with well-preserved ruins and sculptures',
        4.5,
        '11th-12th Century',
        'LKR 3500 (Foreign), LKR 50 (Local)',
        '7:00 AM - 6:00 PM',
        TRUE
    ),
    (
        'Anuradhapura Sacred City',
        'Anuradhapura',
        'North Central',
        'North Central Province',
        'Archaeological Site',
        'Ancient capital and sacred city with Buddhist monuments',
        4.7,
        '4th Century BC',
        'LKR 3500 (Foreign), LKR 50 (Local)',
        '6:00 AM - 6:00 PM',
        TRUE
    ),
    (
        'Kelaniya Raja Maha Vihara',
        'Kelaniya',
        'Western',
        'Western Province',
        'Buddhist Temple',
        'Historic temple with beautiful murals and religious significance',
        4.4,
        '3rd Century BC',
        'Free',
        '5:00 AM - 10:00 PM',
        FALSE
    ),
    (
        'Gangaramaya Temple',
        'Colombo',
        'Western',
        'Western Province',
        'Buddhist Temple',
        'Important temple with museum and library in heart of Colombo',
        4.3,
        '19th Century',
        'LKR 300',
        '6:00 AM - 10:00 PM',
        FALSE
    ),
    (
        'Isurumuniya Temple',
        'Anuradhapura',
        'North Central',
        'North Central Province',
        'Buddhist Temple',
        'Ancient temple famous for its rock carvings and sculptures',
        4.5,
        '3rd Century BC',
        'LKR 200',
        '8:00 AM - 6:00 PM',
        FALSE
    ),
    (
        'Buduruwagala Temple',
        'Wellawaya',
        'Uva',
        'Uva Province',
        'Buddhist Site',
        'Ancient rock temple with carved Buddha figures',
        4.2,
        '10th Century',
        'LKR 500',
        '6:00 AM - 6:00 PM',
        FALSE
    ),
    (
        'Mulkirigala Temple',
        'Tangalle',
        'Southern',
        'Southern Province',
        'Buddhist Temple',
        'Rock temple complex with caves and frescoes',
        4.3,
        '3rd Century BC',
        'LKR 500',
        '6:00 AM - 6:00 PM',
        FALSE
    );
INSERT INTO wildlife_parks (
        name,
        location,
        region,
        province,
        type,
        description,
        rating,
        animals_seen,
        best_time_to_visit,
        entrance_fee,
        area_sqkm
    )
VALUES (
        'Yala National Park',
        'Hambantota',
        'Southern',
        'Southern Province',
        'National Park',
        'Most visited national park known for leopards and diverse wildlife',
        4.7,
        'Leopards, elephants, sloth bears, crocodiles, birds, deer',
        'February to June',
        'LKR 4000 (Foreign), LKR 250 (Local)',
        979
    ),
    (
        'Udawalawe National Park',
        'Udawalawe',
        'Sabaragamuwa',
        'Sabaragamuwa Province',
        'National Park',
        'Famous for large elephant herds and bird watching',
        4.5,
        'Elephants, water buffalo, crocodiles, birds, sambar deer',
        'Year-round',
        'LKR 4000 (Foreign), LKR 250 (Local)',
        308
    ),
    (
        'Wilpattu National Park',
        'Puttalam',
        'North Western',
        'North Western Province',
        'National Park',
        'Largest national park with unique natural lakes called villus',
        4.4,
        'Leopards, elephants, deer, crocodiles, birds',
        'February to October',
        'LKR 4000 (Foreign), LKR 250 (Local)',
        1317
    ),
    (
        'Sinharaja Forest Reserve',
        'Ratnapura',
        'Sabaragamuwa',
        'Sabaragamuwa Province',
        'Rainforest Reserve',
        'UNESCO World Heritage rainforest with endemic species',
        4.6,
        'Endemic birds, reptiles, amphibians, insects, purple-faced langur',
        'January to April, August to September',
        'LKR 2000 (Foreign), LKR 100 (Local)',
        111
    ),
    (
        'Minneriya National Park',
        'Habarana',
        'North Central',
        'North Central Province',
        'National Park',
        'Famous for "The Gathering" - largest elephant congregation in Asia',
        4.5,
        'Elephants, deer, birds, crocodiles, monkeys',
        'June to September',
        'LKR 3500 (Foreign), LKR 200 (Local)',
        89
    ),
    (
        'Bundala National Park',
        'Hambantota',
        'Southern',
        'Southern Province',
        'National Park',
        'Important wetland sanctuary and bird watching destination',
        4.3,
        'Migratory birds, crocodiles, elephants, flamingos',
        'September to March',
        'LKR 3000 (Foreign), LKR 150 (Local)',
        62
    ),
    (
        'Kaudulla National Park',
        'Habarana',
        'North Central',
        'North Central Province',
        'National Park',
        'Elephant park with ancient reservoir and diverse wildlife',
        4.2,
        'Elephants, deer, birds, fishing cats, wild boar',
        'August to December',
        'LKR 3500 (Foreign), LKR 200 (Local)',
        66
    ),
    (
        'Kumana National Park',
        'Arugam Bay',
        'Eastern',
        'Eastern Province',
        'National Park',
        'Bird sanctuary with over 200 species and pristine beaches',
        4.4,
        'Birds, elephants, leopards, crocodiles, sea turtles',
        'April to July',
        'LKR 3500 (Foreign), LKR 200 (Local)',
        357
    );
INSERT INTO tea_estates (
        name,
        location,
        region,
        province,
        description,
        rating,
        tea_types,
        tour_available,
        tasting_available,
        opening_hours,
        altitude_m
    )
VALUES (
        'Pedro Tea Estate',
        'Nuwara Eliya',
        'Central',
        'Central Province',
        'Historic tea estate with scenic views and traditional processing',
        4.5,
        'Black tea, Pekoe, Orange Pekoe, Broken Orange Pekoe',
        TRUE,
        TRUE,
        '8:00 AM - 5:00 PM',
        1800
    ),
    (
        'Mackwoods Labookellie Tea Centre',
        'Nuwara Eliya',
        'Central',
        'Central Province',
        'Popular tea factory with museum and tasting room',
        4.4,
        'High grown Ceylon tea, flavored teas, green tea',
        TRUE,
        TRUE,
        '8:30 AM - 4:30 PM',
        1900
    ),
    (
        'Handunugoda Tea Estate',
        'Ahangama',
        'Southern',
        'Southern Province',
        'Unique low country tea estate with virgin white tea',
        4.6,
        'Virgin white tea, flavored teas, white tea, green tea',
        TRUE,
        TRUE,
        '8:00 AM - 5:00 PM',
        100
    ),
    (
        'Dunkeld Tea Estate',
        'Hatton',
        'Central',
        'Central Province',
        'Scenic tea estate in Dickoya valley with factory tours',
        4.3,
        'High grown black tea, BOPF, Pekoe grades',
        TRUE,
        TRUE,
        '8:00 AM - 4:00 PM',
        1500
    ),
    (
        'Blue Field Tea Gardens',
        'Ramboda',
        'Central',
        'Central Province',
        'Picturesque tea estate with waterfall views',
        4.2,
        'High grown Ceylon tea, Orthodox tea',
        TRUE,
        TRUE,
        '8:30 AM - 4:30 PM',
        1200
    ),
    (
        'Lipton\'s Seat',
        'Haputale',
        'Uva',
        'Uva Province',
        'Historic viewpoint and tea estate with panoramic views',
        4.7,
        'Uva highland tea, premium grades',
        TRUE,
        FALSE,
        '6:00 AM - 6:00 PM',
        1970
    );
INSERT INTO activities (
        name,
        location,
        region,
        category,
        description,
        rating,
        price_range,
        duration,
        difficulty_level,
        booking_required
    )
VALUES (
        'White Water Rafting',
        'Kitulgala',
        'Sabaragamuwa',
        'Adventure',
        'Thrilling rafting experience on Kelani River through rainforest',
        4.6,
        '$30-50',
        '3-4 hours',
        'Moderate',
        TRUE
    ),
    (
        'Hot Air Ballooning',
        'Dambulla',
        'Central',
        'Adventure',
        'Scenic balloon rides over cultural triangle and countryside',
        4.8,
        '$200-300',
        '3 hours',
        'Easy',
        TRUE
    ),
    (
        'Whale Watching',
        'Mirissa',
        'Southern',
        'Wildlife',
        'Boat excursions to see blue whales and dolphins',
        4.7,
        '$25-40',
        '4-5 hours',
        'Easy',
        TRUE
    ),
    (
        'Trekking to Adam\'s Peak',
        'Hatton',
        'Central',
        'Adventure',
        'Sacred mountain trek with sunrise views',
        4.9,
        'Free-$10',
        '4-6 hours',
        'Challenging',
        FALSE
    ),
    (
        'Surfing Lessons',
        'Arugam Bay',
        'Eastern',
        'Water Sports',
        'Learn to surf at one of Asia\'s best surf breaks',
        4.5,
        '$20-40',
        '2-3 hours',
        'Beginner to Advanced',
        TRUE
    ),
    (
        'Cycling in Cultural Triangle',
        'Anuradhapura',
        'North Central',
        'Cultural',
        'Bicycle tours through ancient ruins and temples',
        4.4,
        '$15-30',
        'Full day',
        'Easy',
        TRUE
    ),
    (
        'Spice Garden Tour',
        'Matale',
        'Central',
        'Cultural',
        'Learn about Sri Lankan spices and traditional medicine',
        4.3,
        '$10-20',
        '2 hours',
        'Easy',
        FALSE
    ),
    (
        'Turtle Watching',
        'Kosgoda',
        'Western',
        'Wildlife',
        'Visit turtle hatchery and watch turtle releases',
        4.5,
        '$5-15',
        '1-2 hours',
        'Easy',
        FALSE
    );
INSERT INTO transport (
        type,
        route,
        operator,
        description,
        price_range,
        schedule_info,
        duration,
        frequency
    )
VALUES (
        'Train',
        'Colombo to Kandy',
        'Sri Lanka Railways',
        'Scenic train journey through hill country',
        '$2-15',
        'Multiple daily services',
        '3 hours',
        'Every 2 hours'
    ),
    (
        'Train',
        'Kandy to Ella',
        'Sri Lanka Railways',
        'One of world\'s most beautiful train rides',
        '$3-20',
        '3 daily services',
        '7 hours',
        '3 times daily'
    ),
    (
        'Bus',
        'Colombo to Galle',
        'SLTB/Private',
        'Coastal highway bus service',
        '$2-5',
        'Frequent services',
        '2.5 hours',
        'Every 30 minutes'
    ),
    (
        'Taxi/Tuk-tuk',
        'City transport',
        'Various operators',
        'Local transportation in cities and towns',
        '$0.5-20',
        'On demand',
        'Varies',
        'On demand'
    ),
    (
        'Private Vehicle',
        'Airport transfers',
        'Various operators',
        'Private car hire with driver',
        '$30-100',
        'Pre-booked',
        'Varies',
        'On demand'
    ),
    (
        'Boat',
        'Negombo lagoon tours',
        'Local operators',
        'Boat tours through mangroves and fishing villages',
        '$10-25',
        'Daily tours',
        '2-3 hours',
        'Multiple daily'
    ),
    (
        'Domestic Flight',
        'Colombo to Trincomalee',
        'Cinnamon Air/FitsAir',
        'Domestic flights to remote destinations',
        '$80-150',
        'Limited schedule',
        '45 minutes',
        'Few weekly'
    );
INSERT INTO events (
        id,
        name,
        location,
        region,
        type,
        description,
        date_period,
        significance,
        annual_event
    )
VALUES (
        1,
        'Esala Perahera',
        'Kandy',
        'Central',
        'Religious Festival',
        'Grand procession with elephants, dancers, and drummers',
        'July-August',
        'Most important Buddhist festival in Sri Lanka',
        TRUE
    ),
    (
        2,
        'Vesak Festival',
        'Nationwide',
        'All',
        'Religious Festival',
        'Celebration of Buddha''s birth, enlightenment, and death',
        'May',
        'Most important Buddhist holiday with decorations and lanterns',
        TRUE
    ),
    (
        3,
        'Sinhala and Tamil New Year',
        'Nationwide',
        'All',
        'Cultural Festival',
        'Traditional New Year celebration with rituals and games',
        'April',
        'Most important cultural celebration of the year',
        TRUE
    ),
    (
        4,
        'Colombo Fashion Week',
        'Colombo',
        'Western',
        'Fashion Event',
        'International fashion event showcasing local and regional designers',
        'March/October',
        'Premier fashion event in South Asia',
        TRUE
    ),
    (
        5,
        'Galle Literary Festival',
        'Galle',
        'Southern',
        'Cultural Event',
        'International literature festival in historic Galle Fort',
        'January',
        'Prestigious literary event attracting world-renowned authors',
        TRUE
    ),
    (
        6,
        'Nallur Festival',
        'Jaffna',
        'Northern',
        'Religious Festival',
        'Hindu festival with chariot processions and cultural performances',
        'July-August',
        'Most important Hindu festival in Northern Sri Lanka',
        TRUE
    ),
    (
        7,
        'Duruthu Perahera',
        'Kelaniya',
        'Western',
        'Religious Festival',
        'Buddhist procession commemorating Buddha''s visit to Sri Lanka',
        'January',
        'Important Buddhist festival with traditional procession',
        TRUE
    );
INSERT INTO hotels (
        name,
        location,
        region,
        province,
        accommodation_type,
        rating,
        price_range,
        amenities,
        description,
        room_count
    )
VALUES (
        'The Thinnai',
        'Jaffna',
        'Northern',
        'Northern Province',
        'Boutique Hotel',
        4.6,
        '$100-200',
        'Swimming pool, restaurant, bike rentals, WiFi',
        'Boutique hotel with modern amenities and Northern charm',
        40
    ),
    (
        'Anantaya Resort & Spa',
        'Chilaw',
        'North Western',
        'North Western Province',
        'Resort',
        4.5,
        '$150-250',
        'Beachfront, spa, multiple pools, restaurant, gym',
        'Luxury resort situated between the Indian Ocean and a lagoon',
        87
    ),
    (
        'Jetwing Lake',
        'Dambulla',
        'Central',
        'Central Province',
        'Luxury Hotel',
        4.7,
        '$180-300',
        'Infinity pool, spa, nature walks, lake view, WiFi',
        'Luxurious hotel offering serene views of the Dambulla Lake',
        100
    ),
    (
        'Uga Ulagalla',
        'Thirappane',
        'North Central',
        'North Central Province',
        'Boutique Hotel',
        4.9,
        '$400-600',
        'Private villas, private pool, spa, horse riding, WiFi',
        'Luxury boutique hotel with private villas in a 58-acre sanctuary',
        20
    ),
    (
        '98 Acres Resort & Spa',
        'Ella',
        'Uva',
        'Uva Province',
        'Eco Resort',
        4.8,
        '$150-300',
        'Infinity pool, spa, mountain views, restaurant, hiking trails',
        'Eco-friendly resort surrounded by a tea plantation',
        30
    );
INSERT INTO restaurants (
        name,
        location,
        region,
        cuisine,
        rating,
        price_range,
        specialties,
        description,
        opening_hours
    )
VALUES (
        'Nuga Gama',
        'Cinnamon Grand Colombo',
        'Western',
        'Traditional Sri Lankan',
        4.6,
        '$15-30',
        'Authentic village-style rice and curry, hoppers, Sri Lankan sweets',
        'An open-air restaurant replicating a traditional Sri Lankan village',
        '7:00 PM - 10:30 PM'
    ),
    (
        'Sea Spray Restaurant',
        'Mount Lavinia Hotel',
        'Western',
        'Seafood',
        4.5,
        '$20-45',
        'Fresh seafood, lobster, prawns, grilled fish, ocean view dining',
        'Oceanfront dining with panoramic views of the Indian Ocean',
        '7:00 PM - 11:00 PM'
    ),
    (
        'Curry Leaf',
        'Hilton Colombo',
        'Western',
        'Sri Lankan',
        4.4,
        '$18-40',
        'Authentic Sri Lankan buffet with live cooking stations',
        'An authentic buffet restaurant serving local dishes',
        '7:00 PM - 11:00 PM'
    ),
    (
        'Lucky Fort Restaurant',
        'Galle Fort',
        'Southern',
        'Sri Lankan',
        4.7,
        '$8-18',
        '10-curry buffet, rice and curry, kottu, fresh juices',
        'Family-run restaurant famous for its traditional 10-curry meal',
        '9:00 AM - 10:00 PM'
    ),
    (
        'The Hideout',
        'Ella',
        'Uva',
        'International/Pub',
        4.5,
        '$5-15',
        'Pizza, burgers, cocktails, live music',
        'Relaxed pub with great food and a lively atmosphere',
        '11:00 AM - 12:00 AM'
    );
INSERT INTO attractions (
        name,
        description,
        location,
        region,
        province,
        category,
        rating,
        entrance_fee,
        opening_hours,
        best_time_to_visit,
        distance_from_colombo,
        facilities
    )
VALUES (
        'Lipton\'s Seat',
        'Historic viewpoint and tea estate with panoramic views of surrounding hills',
        'Haputale',
        'Uva',
        'Uva Province',
        'Scenic',
        4.7,
        'LKR 500 (Foreign), LKR 100 (Local)',
        '6:00 AM - 6:00 PM',
        'January to March',
        205,
        'Viewpoints, tea stalls, parking'
    ),
    (
        'Little Adam\'s Peak',
        'A scenic and easy hike with stunning panoramic views of Ella',
        'Ella',
        'Uva',
        'Uva Province',
        'Nature/Adventure',
        4.6,
        'Free',
        'Always accessible',
        'Year-round',
        200,
        'Rest stops, small shops'
    ),
    (
        'Yala National Park',
        'Most visited national park known for leopards and diverse wildlife',
        'Hambantota',
        'Southern',
        'Southern Province',
        'Wildlife',
        4.7,
        'LKR 4000 (Foreign), LKR 250 (Local)',
        '6:00 AM - 6:00 PM',
        'February to June',
        260,
        'Safari jeeps, guide services, restrooms'
    );
INSERT INTO beaches (
        name,
        location,
        region,
        province,
        description,
        rating,
        activities,
        best_time_to_visit,
        facilities,
        water_sports_available,
        lifeguard_available
    )
VALUES (
        'Nilaveli Beach',
        'Trincomalee',
        'Eastern',
        'Eastern Province',
        'Pristine white sand beach with clear shallow waters',
        4.6,
        'Swimming, snorkeling, Pigeon Island trips, diving',
        'May to October',
        'Resorts, guesthouses, dive centers, boat services',
        TRUE,
        TRUE
    ),
    (
        'Uppuveli Beach',
        'Trincomalee',
        'Eastern',
        'Eastern Province',
        'Calm beach with less crowds, perfect for relaxation',
        4.4,
        'Swimming, sunbathing, snorkeling, fishing',
        'May to October',
        'Hotels, restaurants, guesthouses',
        TRUE,
        TRUE
    ),
    (
        'Koggala Beach',
        'Koggala',
        'Southern',
        'Southern Province',
        'Famous for stilt fishermen and serene environment',
        4.1,
        'Swimming, sunbathing, stilt fishermen photography',
        'December to March',
        'Stilt fishermen, resorts, cafes',
        FALSE,
        FALSE
    );
INSERT INTO cultural_sites (
        name,
        location,
        region,
        province,
        type,
        description,
        rating,
        historical_period,
        entrance_fee,
        opening_hours,
        unesco_site
    )
VALUES (
        'Jaffna Fort',
        'Jaffna',
        'Northern',
        'Northern Province',
        'Archaeological Site',
        'Historic fort built by the Portuguese and Dutch in Jaffna',
        4.2,
        '17th Century',
        'Free',
        '8:00 AM - 6:00 PM',
        FALSE
    ),
    (
        'Nallur Kandaswamy Kovil',
        'Jaffna',
        'Northern',
        'Northern Province',
        'Hindu Temple',
        'Important Hindu temple with rich history and architectural beauty',
        4.8,
        '15th Century',
        'Free',
        '5:00 AM - 9:00 PM',
        FALSE
    ),
    (
        'Kandy Esala Perahera',
        'Kandy',
        'Central',
        'Religious/Cultural',
        'Annual festival featuring a grand procession with adorned elephants, dancers, and drummers',
        4.9,
        'Historical',
        'Free',
        'Annual Event (July/August)',
        FALSE
    ),
    (
        'Golden Temple of Dambulla',
        'Dambulla',
        'Central',
        'Central Province',
        'Buddhist Temple',
        'A cave temple complex with stunning rock paintings and statues',
        4.6,
        '1st Century BC',
        'LKR 1500 (Foreign)',
        '7:00 AM - 7:00 PM',
        TRUE
    );
INSERT INTO wildlife_parks (
        name,
        location,
        region,
        province,
        type,
        description,
        rating,
        animals_seen,
        best_time_to_visit,
        entrance_fee,
        area_sqkm
    )
VALUES (
        'Hikkaduwa National Park',
        'Hikkaduwa',
        'Southern',
        'Southern Province',
        'Marine Park',
        'A marine park known for its coral reefs and sea turtles',
        4.3,
        'Corals, marine turtles, fish species',
        'November to April',
        'LKR 1000 (Foreign)',
        0.04
    ),
    (
        'Sinharaja Forest Reserve',
        'Sinharaja',
        'Sabaragamuwa',
        'Sabaragamuwa Province',
        'Rainforest Reserve',
        'A UNESCO World Heritage Site known for its biodiversity and endemic species',
        4.6,
        'Endemic birds, reptiles, amphibians, insects',
        'January to April, August to September',
        'LKR 2000 (Foreign)',
        111
    );
INSERT INTO tea_estates (
        name,
        location,
        region,
        province,
        description,
        rating,
        tea_types,
        tour_available,
        tasting_available,
        opening_hours,
        altitude_m
    )
VALUES (
        'Damro Labookellie Tea Centre',
        'Nuwara Eliya',
        'Central',
        'Central Province',
        'A well-known tea factory and tea lounge in the hill country',
        4.4,
        'Black tea, Green tea, White tea',
        TRUE,
        TRUE,
        '8:30 AM - 5:00 PM',
        1850
    ),
    (
        'Halpewatte Tea Factory',
        'Badulla',
        'Uva',
        'Uva Province',
        'One of the largest tea factories in the Uva region',
        4.2,
        'Black tea, Silver tips, Golden tips',
        TRUE,
        TRUE,
        '9:00 AM - 4:00 PM',
        1400
    );
INSERT INTO activities (
        name,
        location,
        region,
        category,
        description,
        rating,
        price_range,
        duration,
        difficulty_level,
        booking_required
    )
VALUES (
        'Hot Air Ballooning',
        'Sigiriya',
        'Central',
        'Adventure',
        'A scenic balloon ride over the Sigiriya Rock Fortress and surrounding area',
        4.8,
        '$200-300',
        '3 hours',
        'Easy',
        TRUE
    ),
    (
        'Whale Watching',
        'Trincomalee',
        'Eastern',
        'Wildlife',
        'Boat tours to spot blue whales and sperm whales in the deep sea',
        4.7,
        '$25-40',
        '4-5 hours',
        'Easy',
        TRUE
    ),
    (
        'Hiking to Horton Plains',
        'Nuwara Eliya',
        'Central',
        'Adventure',
        'A scenic trek to World''s End and Baker''s Falls',
        4.4,
        'LKR 3000 (Foreign)',
        '3-4 hours',
        'Moderate',
        FALSE
    );
INSERT INTO transport (
        type,
        route,
        operator,
        description,
        price_range,
        schedule_info,
        duration,
        frequency
    )
VALUES (
        'Train',
        'Ella to Haputale',
        'Sri Lanka Railways',
        'A picturesque train ride through the highlands and tea plantations',
        '$1-5',
        'Multiple daily services',
        '1 hour',
        'Frequent'
    ),
    (
        'Bus',
        'Colombo to Jaffna',
        'SLTB/Private',
        'Long-distance bus service connecting the capital and the north',
        '$8-15',
        'Daily services',
        '8-10 hours',
        'Multiple daily'
    );
INSERT INTO attractions (
        name,
        description,
        location,
        region,
        province,
        category,
        rating,
        entrance_fee,
        opening_hours,
        best_time_to_visit,
        distance_from_colombo,
        facilities
    )
VALUES (
        'Diyaluma Falls',
        'Second highest waterfall in Sri Lanka, popular for hiking and swimming',
        'Koslanda',
        'Uva',
        'Uva Province',
        'Nature',
        4.8,
        'Free',
        'Always accessible',
        'Year-round',
        220,
        'Local guides, viewpoints, swimming spots'
    ),
    (
        'Udawalawe National Park',
        'Known for its large population of elephants and abundant wildlife',
        'Udawalawe',
        'Sabaragamuwa',
        'Sabaragamuwa Province',
        'Wildlife',
        4.5,
        'LKR 4000 (Foreign)',
        '6:00 AM - 6:00 PM',
        'Year-round',
        180,
        'Safari jeeps, guide services, restrooms'
    ),
    (
        'Jaffna Fort',
        'A historic fort built by the Portuguese and later developed by the Dutch',
        'Jaffna',
        'Northern',
        'Northern Province',
        'Historical',
        4.2,
        'Free',
        '8:00 AM - 6:00 PM',
        'Year-round',
        400,
        'Parking, information boards'
    ),
    (
        'Gangaramaya Temple',
        'An important Buddhist temple in Colombo with a museum and a library',
        'Colombo',
        'Western',
        'Western Province',
        'Religious',
        4.3,
        'LKR 300',
        '6:00 AM - 10:00 PM',
        'Year-round',
        0,
        'Museum, library, parking'
    );
INSERT INTO hotels (
        name,
        location,
        region,
        province,
        accommodation_type,
        rating,
        price_range,
        amenities,
        description,
        room_count
    )
VALUES (
        'Earls Regency',
        'Kandy',
        'Central',
        'Central Province',
        'Luxury Hotel',
        4.6,
        '$150-300',
        'Swimming pool, spa, restaurant, mountain views, WiFi',
        'A luxurious hotel with stunning views of the Mahaweli River',
        100
    ),
    (
        'Amaya Lake Dambulla',
        'Dambulla',
        'Central',
        'Central Province',
        'Eco Resort',
        4.4,
        '$120-250',
        'Swimming pool, spa, cultural shows, restaurant, lake view',
        'A peaceful resort with chalets nestled in a natural setting',
        92
    ),
    (
        'Jetwing St. Andrew\'s',
        'Nuwara Eliya',
        'Central',
        'Central Province',
        'Heritage Hotel',
        4.5,
        '$130-280',
        'Colonial charm, billiard room, restaurant, garden',
        'A colonial-era hotel with a traditional English country-house feel',
        60
    );
INSERT INTO restaurants (
        name,
        location,
        region,
        cuisine,
        rating,
        price_range,
        specialties,
        description,
        opening_hours
    )
VALUES (
        'The Empire Café',
        'Kandy',
        'Central',
        'International',
        4.5,
        '$10-25',
        'Coffee, cakes, light meals, sandwiches',
        'A quaint cafe located near the Temple of the Tooth',
        '8:00 AM - 10:00 PM'
    ),
    (
        'Matey Hut',
        'Ella',
        'Uva',
        'Sri Lankan',
        4.8,
        '$5-10',
        'Traditional rice and curry, kottu, rotti',
        'A small, popular local eatery famous for its home-cooked meals',
        '8:00 AM - 10:00 PM'
    ),
    (
        'The Grand Indian',
        'Nuwara Eliya',
        'Central',
        'Indian',
        4.3,
        '$10-20',
        'Biryani, tandoori, curries, Indian bread',
        'A restaurant specializing in North Indian cuisine',
        '12:00 PM - 10:00 PM'
    );
INSERT INTO activities (
        name,
        location,
        region,
        category,
        description,
        rating,
        price_range,
        duration,
        difficulty_level,
        booking_required
    )
VALUES (
        'Kayaking',
        'Bentota River',
        'Western',
        'Water Sports',
        'Kayaking on the tranquil Bentota River, spotting wildlife',
        4.4,
        '$15-30',
        '2-3 hours',
        'Easy',
        TRUE
    ),
    (
        'Kitesurfing',
        'Kalpitiya',
        'North Western',
        'Water Sports',
        'Kitesurfing lessons and rentals in the windy lagoons',
        4.6,
        '$50-100',
        'Full day',
        'Intermediate to Advanced',
        TRUE
    ),
    (
        'Safari at Kaudulla',
        'Habarana',
        'North Central',
        'Wildlife',
        'A jeep safari to see the large elephant herds at Kaudulla National Park',
        4.2,
        '$40-60',
        '3-4 hours',
        'Easy',
        TRUE
    ),
    (
        'Cooking Class',
        'Ella',
        'Uva',
        'Cultural',
        'Learn to cook traditional Sri Lankan rice and curry',
        4.7,
        '$20-40',
        '3 hours',
        'Easy',
        TRUE
    );
INSERT INTO cultural_sites (
        name,
        location,
        region,
        province,
        type,
        description,
        rating,
        historical_period,
        entrance_fee,
        opening_hours,
        unesco_site
    )
VALUES (
        'Ritigala Forest Monastery',
        'Ritigala',
        'North Central',
        'North Central Province',
        'Archaeological Site',
        'Ancient Buddhist monastery ruins with stone pathways and buildings',
        4.3,
        '1st Century BC',
        'LKR 500',
        '8:00 AM - 5:00 PM',
        FALSE
    ),
    (
        'Yapahuwa Fortress',
        'Yapahuwa',
        'North Western',
        'North Western Province',
        'Archaeological Site',
        'A rock fortress with a magnificent ornamental stairway',
        4.1,
        '13th Century',
        'LKR 500',
        '8:00 AM - 6:00 PM',
        FALSE
    );
CREATE INDEX idx_attractions_region ON attractions(region);
CREATE INDEX idx_attractions_category ON attractions(category);
CREATE INDEX idx_attractions_rating ON attractions(rating);
CREATE INDEX idx_hotels_region ON hotels(region);
CREATE INDEX idx_hotels_rating ON hotels(rating);
CREATE INDEX idx_restaurants_cuisine ON restaurants(cuisine);
CREATE INDEX idx_beaches_region ON beaches(region);
CREATE INDEX idx_cultural_sites_type ON cultural_sites(type);
CREATE INDEX idx_wildlife_parks_type ON wildlife_parks(type);
CREATE VIEW top_attractions AS
SELECT name,
    location,
    region,
    category,
    rating,
    description
FROM attractions
WHERE rating >= 4.5
ORDER BY rating DESC;
CREATE VIEW beach_destinations AS
SELECT b.name,
    b.location,
    b.region,
    b.rating,
    b.activities,
    h.name as nearby_hotel,
    h.rating as hotel_rating
FROM beaches b
    LEFT JOIN hotels h ON b.region = h.region
WHERE b.rating >= 4.0;
CREATE VIEW heritage_sites AS
SELECT name,
    location,
    type,
    historical_period,
    significance,
    entrance_fee,
    rating,
    unesco_site
FROM cultural_sites
ORDER BY rating DESC;
COMMIT;